version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    # docker-executor を使用
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment: 
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        command: |
          mysqld --default-authentication-plugin=mysql_native_password
        environment: 
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password

    # steps を実行する際のディレクトリを指定
    working_directory: ~/rails6-circleci

    steps:
      # プロジェクトのソースコードをジョブの working_directory にチェックアウト
      - checkout

      # gem をインストール
      - run:
          name: Install dependencies
          command: bundle install

      # DBをセットアップ
      - run:
          name: Setup database
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 100s
            bundle exec rails db:create
            bundle exec rails db:schema:load

      # rspec による自動テスト
      - run:
          name: Rspec
          command: bundle exec rspec
      
      # rubocop によるコード解析
      - run:
          name: Rubocop
          command: bundle exec rubocop